### ISSUE TITLE
Seems like the spawning is random

### ISSUE THREAD

**Issue by SRZIsHere** [brian8544/TwitchTV-viewbot#1]
Hello there !

I'm trying the bot, it seems that it works almost perfectly, the only issue is that if we spawn for example 30 clients, it will spawn only a third of them

I'm using Python 3.10.5
(On my PC, the bot is not working with Python 3.11)

**Comment by SRZIsHere** [comment]
Some news :
I was working with Python 3.10.5

Updated to 3.11, then did : pip install -r requirements.txt

Now, when I type the number of virtual viewer that I want it crash

**Comment by brian8544** [comment]
You're right. This is not due to this script, it's cause of the listed proxy_servers being overloaded or not succesfully loading the TTV page. Which you can see for yourself by commenting this part `chrome_options.add_argument('--headless')`. I've been looking into VPN/HTTP proxy alternatives. But most seem blocked by TTV (as it should).

**Comment by SRZIsHere** [comment]
Oh okay thanks !

Is there a way to contact you with Discord or something else ?
